sakura_rental_servers:
  hosts:
    "example.sakura.ne.jp":
      ansible_host: wwwXXXXXX.sakura.ne.jp
      ansible_user: example
      ansible_ssh_pass: ex@mple_user_p@55w0rd
      ansible_connection: paramiko
  vars:
    ansible_python_interpreter: /usr/local/bin/python
