sakura_rental_servers:
  hosts:
    "<ここに初期ドメインを設定します>":
      ansible_host: "<ここにホスト名を設定します>"
      ansible_user: "<ここにFTPアカウントを設定します>"
      ansible_ssh_pass: "<ここにサーバパスワードを設定します>"
      ansible_connection: paramiko
  vars:
    ansible_python_interpreter: /usr/local/bin/python
