- name: Sakura Rental Server WordPress Setup tool
  hosts: sakura_rental_servers
  become: no
  gather_facts: no
  tasks:
    - name: Load setting file
      include_vars: config.yml
      tags: always
    - name: Set authorized key
      authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ item.key }}"
        state: "{{ 'present' if item.state|default(true) else 'absent' }}"
      with_items: "{{ authorized_keys }}"
      tags: authorized_key
    - name: Create user directories
      file:
        path: "~/{{ item }}"
        state: directory
      with_items:
        - bin
        - tmp
        - backup
      tags: always
    - name: Setup usacloud
      import_tasks: tasks/usacloud.yml
      tags: usacloud
    - name: Setup PHP
      import_tasks: tasks/php.yml
      tags: php
    - name: Setup WordPress
      import_tasks: tasks/wordpress.yml
      tags: wordpress
    - name: Setup MySQL connection setting
      import_tasks: tasks/mysql.yml
      tags: mysql
