- name: Cleanup usacloud files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - ~/bin/usacloud
    - ~/tmp/usacloud_freebsd-amd64.zip
- block:
    - name: Dowload usacloud
      command: wget https://github.com/sacloud/usacloud/releases/download/v{{ usacloud.version }}/usacloud_freebsd-amd64.zip -O usacloud_freebsd-amd64.zip
      args:
        chdir: ~/tmp
        warn: no
    - name: Install usacloud
      unarchive:
        src: ~/tmp/usacloud_freebsd-amd64.zip
        dest: ~/bin
        remote_src: yes
    - name: Create usacloud default Setting file directory
      file:
        path: ~/.usacloud/default
        state: directory
    - name: Set usacloud default setting variable
      set_fact:
        usacloud_default_config:
          AccessToken: "{{ usacloud.token }}"
          AccessTokenSecret: "{{ usacloud.secret }}"
          Zone: "{{ usacloud.zone }}"
          DefaultOutputType: "{{ usacloud.output_type }}"
    - name: Create usacloud default setting file
      copy:
        content: "{{ usacloud_default_config | to_nice_json }}"
        dest: ~/.usacloud/default/config.json
    - name: Set environment variables
      lineinfile:
        path: ~/.cshrc
        regexp: "setenv\\s+{{ item.name }}\\s+"
        line: "setenv {{ item.name }} \"{{ item.value }}\""
      with_items:
        - name: SACLOUD_OJS_ACCESS_KEY_ID
          value: "{{ usacloud.ojs_access_key_id }}"
        - name: SACLOUD_OJS_SECRET_ACCESS_KEY
          value: "{{ usacloud.ojs_secret_access_key }}"
  when: usacloud.install
