- name: Cleanup usacloud files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - ~/bin/usacloud
    - ~/tmp/usacloud_freebsd-amd64.zip
- block:
    - name: Dowload usacloud
      command: wget https://github.com/sacloud/usacloud/releases/download/v{{ usacloud.version }}/usacloud_freebsd-amd64.zip -O usacloud_freebsd-amd64.zip
      args:
        chdir: ~/tmp
        warn: no
    - name: Install usacloud
      unarchive:
        src: ~/tmp/usacloud_freebsd-amd64.zip
        dest: ~/bin
        remote_src: yes
    - name: Create usacloud default Setting file directory
      file:
        path: ~/.usacloud/default
        state: directory
    - name: Set usacloud default setting variable
      set_fact:
        usacloud_default_config:
          AccessToken: "{{ usacloud.token }}"
          AccessTokenSecret: "{{ usacloud.secret }}"
          Zone: "{{ usacloud.zone }}"
          DefaultOutputType: "{{ usacloud.output_type }}"
    - name: Create usacloud default setting file
      copy:
        content: "{{ usacloud_default_config | to_nice_json }}"
        dest: ~/.usacloud/default/config.json
    - name: Set environment variables(SACLOUD_OJS_ACCESS_KEY_ID)
      lineinfile:
        path: ~/.cshrc
        regexp: "setenv\\s+SACLOUD_OJS_ACCESS_KEY_ID\\s+"
        line: "setenv SACLOUD_OJS_ACCESS_KEY_ID \"{{ usacloud.ojs_access_key_id|default('') }}\""
        state: "{{ 'present' if usacloud.ojs_access_key_id is defined else 'absent' }}"
    - name: Set environment variables(SACLOUD_OJS_SECRET_ACCESS_KEY)
      lineinfile:
        path: ~/.cshrc
        regexp: "setenv\\s+SACLOUD_OJS_SECRET_ACCESS_KEY\\s+"
        line: "setenv SACLOUD_OJS_SECRET_ACCESS_KEY \"{{ usacloud.ojs_secret_access_key|default('') }}\""
        state: "{{ 'present' if usacloud.ojs_secret_access_key is defined else 'absent' }}"
  when: usacloud.install
